const obj = [
  {
    Name: "mail tổng",
    Mail: "teluscanviet2023@gmail.com",
    "New Pass Mail": "Huuviet@1988",
  },
  {
    Stt: 1,
    Mail: "crawmergalleyd1825@gmail.com",
    "New Pass Mail": "cantelusviet@01",
    "Mail Reco": "monyeimegesat@hotmail.com",
    "Pass Telus": "Telus#123",
    DOB: "29/4/1988",
    GEN: "Male",
  },
  {
    Stt: 1,
    Name: "Ben Jones",
    Mail: "hamelinckvanrulerqx3532@gmail.com",
    "New Pass Mail": "cantelusviet@02",
    "Mail Reco": "kihongsunenae@hotmail.com",
    "Pass Telus": "Telus#124",
    DOB: "10/6/1988",
    GEN: "Male",
    ADDRESS: "148 Maynooth Ct, Ottawa, ON K2J 6Y5, Canada",
    City: "Ottawa",
    State: "ON",
    "Zip code": "K2J 6Y5",
    Cmpany: "Royal Bank Of Canada",
    University: "University of Toronto.",
  },
  {
    Stt: 2,
    Name: "Blake Johnston",
    Mail: "kenisonmiyaho1234@gmail.com",
    "New Pass Mail": "cantelusviet@03",
    "Mail Reco": "hamelinckvanrulerqx3532@gmail.com",
    "Pass Telus": "Telus#125",
    DOB: "2/4/1989",
    GEN: "Male",
    ADDRESS: "51 Knockaderry Cres, Ottawa, ON K2C 3H2, Canada",
    City: "Ottawa",
    State: "ON",
    "Zip code": "K2C 3H2",
    Cmpany: "Toronto Dominion Bank",
    University: "McGill University.",
  },
  {
    Stt: 3,
    Name: "Eli Reid",
    Mail: "havirjurneyvq6594@gmail.com",
    "New Pass Mail": "cantelusviet@04",
    "Mail Reco": "kenisonmiyaho1234@gmail.com",
    "Pass Telus": "Telus#126",
    DOB: "4/12/1989",
    GEN: "Male",
    ADDRESS: "151 Damselfly Way, Ottawa, ON K2J 6H6, Canada",
    City: "Ottawa",
    State: "ON",
    "Zip code": "K2J 6H6,",
    Cmpany: "Enbridge",
    University: "University of British Columbia.",
  },
  {
    Stt: 4,
    Name: "Reid Byrne",
    Mail: "flaggerosgo654@gmail.com",
    "New Pass Mail": "cantelusviet@05",
    "Mail Reco": "strayhornnewhallms3250@gmail.com",
    "Pass Telus": "Telus#127",
    DOB: "17/10/1990",
    GEN: "Male",
    ADDRESS: "5982 Woodsworth St, Burnaby, BC V5G 1S8, Canada",
    City: "Burnaby",
    State: "BC",
    "Zip code": "V5G 1S8",
    Cmpany: "Canadian National Railways",
    University: "University of Alberta.",
  },
  {
    Stt: 5,
    Name: "Charlie Stephenson",
    Mail: "strayhornnewhallms3250@gmail.com",
    "New Pass Mail": "cantelusviet@06",
    "Mail Reco": "palmquistcampagnehr5283@gmail.com",
    "Pass Telus": "Telus#128",
    DOB: "5/12/1990",
    GEN: "Male",
    ADDRESS: "5468 Norfolk St, Burnaby, BC V5G 1G2, Canada",
    City: "Burnaby",
    State: "BC",
    "Zip code": "V5G 1G2",
    Cmpany: "Canadian Pacific Railway",
    University: "McMaster University.",
  },
  {
    Stt: 6,
    Name: "Kane Taylor",
    Mail: "palmquistcampagnehr5283@gmail.com",
    "New Pass Mail": "cantelusviet@07",
    "Mail Reco": "hodangwathneyky7830@gmail.com",
    "Pass Telus": "Telus#129",
    DOB: "24/3/1991",
    GEN: "Male",
    ADDRESS: "4951 Manor St, Burnaby, BC V5G 1B4, Canada",
    City: "Burnaby",
    State: "BC",
    "Zip code": "V5G 1B4",
    Cmpany: "Bank of Montreal",
    University: "University of Waterloo.",
  },
  {
    Stt: 7,
    Name: "Markus George",
    Mail: "kooistravirziyd558@gmail.com",
    "New Pass Mail": "cantelusviet@08",
    "Mail Reco": "palmquistcampagnehr5283@gmail.com",
    "Pass Telus": "Telus#130",
    DOB: "26/7/1991",
    GEN: "Male",
    ADDRESS: "67 Natronia Trail, Brampton, ON L6P 3N8, Canada",
    City: "Brampton",
    State: "ON",
    "Zip code": "L6P 3N8",
    Cmpany: "Canadian Natural Resources",
    University: "University of Ottawa.",
  },
  {
    Stt: 8,
    Name: "Tyler Brock",
    Mail: "adamekgadzinskith542@gmail.com",
    "New Pass Mail": "cantelusviet@09",
    "Mail Reco": "kooistravirziyd558@gmail.com",
    "Pass Telus": "Telus#131",
    DOB: "31/7/1991",
    GEN: "Male",
    ADDRESS: "15 High Meadows Rd, Brampton, ON L6P 3P4, Canada",
    City: "Brampton",
    State: "ON",
    "Zip code": "L6P 3P4",
    Cmpany: "Scotiabank",
    University: "University of Calgary.",
  },
  {
    Stt: 9,
    Name: "Aidan Bain",
    Mail: "hodangwathneyky7830@gmail.com",
    "New Pass Mail": "cantelusviet@10",
    "Mail Reco": "tiffingorrgn2895@gmail.com",
    "Pass Telus": "Telus#132",
    DOB: "25/10/1991",
    GEN: "Male",
    ADDRESS: "18 Long Branch Trail, Brampton, ON L6P 0V9, Canada",
    City: "Brampton",
    State: "ON",
    "Zip code": "L6P 0V9",
    Cmpany: "Thomson Reuters",
    University: "Queen’s University.",
  },
  {
    Stt: 10,
    Name: "Zayden Calder",
    Mail: "tiffingorrgn2895@gmail.com",
    "New Pass Mail": "cantelusviet@11",
    "Mail Reco": "bussomcoaltermo5995@gmail.com",
    "Pass Telus": "Telus#133",
    DOB: "7/8/1988",
    GEN: "Male",
    ADDRESS: "78 Washburn Rd, Brampton, ON L6P 0V9, Canada",
    City: "Brampton",
    State: "ON",
    "Zip code": "L6P 0V9",
    Cmpany: "Shopify",
    University: "University of Victoria (UVic)",
  },
  {
    Stt: 11,
    Name: "Lawson Reeves",
    Mail: "bussomcoaltermo5995@gmail.com",
    "New Pass Mail": "cantelusviet@12",
    "Mail Reco": "roskamfitanidesfm9585@gmail.com",
    "Pass Telus": "Telus#134",
    DOB: "1/10/1988",
    GEN: "Male",
    ADDRESS: "5926 164 St, Surrey, BC V3S 6M6, Canada",
    City: "Surrey",
    State: "BC",
    "Zip code": "V3S 6M6",
    Cmpany: "FAQs",
    University: "Alberta Edmonton University",
  },
  {
    Stt: 12,
    Name: "Colt Castle",
    Mail: "champeynordstrandex299@gmail.com",
    "New Pass Mail": "cantelusviet@13",
    "Mail Reco": "roskamfitanidesfm9585@gmail.com",
    "Pass Telus": "Telus#135",
    DOB: "23/12/1988",
    GEN: "Male",
    ADDRESS: "5985 165 St, Surrey, BC V3S 4N9, Canada",
    City: "Surrey",
    State: "BC",
    "Zip code": "V3S 4N9",
    Cmpany: "Brookfield Asset Management",
    University: "Athabasca University",
  },
  {
    Stt: 13,
    Name: "Corbin Todd",
    Mail: "vanbibberhagooddo619@gmail.com",
    "New Pass Mail": "cantelusviet@14",
    "Mail Reco": "champeynordstrandex299@gmail.com",
    "Pass Telus": "Telus#136",
    DOB: "18/8/1989",
    GEN: "Male",
    ADDRESS: "16244 61a Ave, Surrey, BC V3S 3V8, Canada",
    City: "Surrey",
    State: "BC",
    "Zip code": "V3S 3V8",
    Cmpany: "Power Corporation of Canada",
    University: "Calgary Calgary University",
  },
  {
    Stt: 14,
    Name: "Lochlan Moore",
    Mail: "roskamfitanidesfm9585@gmail.com",
    "New Pass Mail": "cantelusviet@15",
    "Mail Reco": "gohsorberwc7157@gmail.com",
    "Pass Telus": "Telus#137",
    DOB: "19/1/1991",
    GEN: "Male",
    ADDRESS: "14135 77 Ave, Surrey, BC V3W 2W8, Canada",
    City: "Surrey",
    State: "BC",
    "Zip code": "V3W 2W8,",
    Cmpany: "Manulife Financial",
    University: "Lethbridge University",
  },
  {
    Stt: 15,
    Name: "Cooper Wright",
    Mail: "gohsorberwc7157@gmail.com",
    "New Pass Mail": "cantelusviet@16",
    "Mail Reco": "detroburchinalfb5215@gmail.com",
    "Pass Telus": "Telus#138",
    DOB: "2/2/1991",
    GEN: "Male",
    ADDRESS: "14140 78 Ave, Surrey, BC V3W 2Y1, Canada",
    City: "Surrey",
    State: "BC ",
    "Zip code": "V3W 2Y1",
    Cmpany: "Royal Bank of Canada",
    University: "Mount Royal University",
  },
  {
    Stt: 16,
    Name: "Vincent Lee",
    Mail: "vanessabaranickes858@gmail.com",
    "New Pass Mail": "cantelusviet@17",
    "Mail Reco": "vanbibberhagooddo619@gmail.com",
    "Pass Telus": "Telus#139",
    DOB: "28/3/1991",
    GEN: "Male",
    ADDRESS: "210 Whispering Waters Rd, Marmora, ON K0K 2M0, Canada",
    City: "Marmora",
    State: "ON ",
    "Zip code": "K0K 2M0",
    Cmpany: "Alimentation Couche-Tard",
    University: "Grant Macewan University",
  },
  {
    Stt: 17,
    Name: "Joseph Gesner",
    Mail: "detroburchinalfb5215@gmail.com",
    "New Pass Mail": "cantelusviet@18",
    "Mail Reco": "teluscanviet2023@gmail.com",
    "Pass Telus": "Telus#140",
    DOB: "8/8/1991",
    GEN: "Male",
    ADDRESS: "228 Bethany Hills Rd, Bethany, ON L0A 1A0, Canada",
    City: "Bethany",
    State: "ON ",
    "Zip code": "L0A 1A0",
    University: "Old Scona, Edmonton",
  },
  {
    Stt: 18,
    Name: "Ayden Mitchell",
    Mail: "quichopouncilip102@gmail.com",
    "New Pass Mail": "cantelusviet@19",
    "Mail Reco": "vanessabaranickes858@gmail.com",
    "Pass Telus": "Telus#141",
    DOB: "26/10/1991",
    GEN: "Male",
    ADDRESS: "3458 Pigram Rd, Salford, ON N0J 1W0, Canada",
    City: "Salford",
    State: "ON ",
    "Zip code": "N0J 1W0",
    University: "Rundle College, Calgary",
  },
  {
    Stt: 19,
    Name: "Kade Goddard",
    Mail: "hottoncancrois824@gmail.com",
    "New Pass Mail": "cantelusviet@20",
    "Mail Reco": "quichopouncilip102@gmail.com",
    "Pass Telus": "Telus#142",
    DOB: "17/12/1991",
    GEN: "Male",
    ADDRESS: "3541 Forbes Rd, Mossley, ON N0L 1V0, Canada",
    City: "Mossley",
    State: "ON ",
    "Zip code": "N0L 1V0",
    University: "St Michael’s Choir",
  },
  {
    Stt: 20,
    Name: "Kingston Sim",
    Mail: "koprivaluccayh806@gmail.com",
    "New Pass Mail": "cantelusviet@21",
    "Mail Reco": "hottoncancrois824@gmail.com",
    "Pass Telus": "Telus#143",
    DOB: "1/5/1988",
    GEN: "Female",
    ADDRESS: "2970 W 22nd Ave, Vancouver, BC V6L 1M8, Canada",
    City: "Vancouver",
    State: "BC ",
    "Zip code": "V6L 1M8",
    University: "York House, Vancouver",
  },
  {
    Stt: 21,
    Name: "Raya Gallant",
    Mail: "stossvanleeryh786@gmail.com",
    "New Pass Mail": "cantelusviet@22",
    "Mail Reco": "koprivaluccayh806@gmail.com",
    "Pass Telus": "Telus#144",
    DOB: "16/6/1988",
    GEN: "Female",
    ADDRESS: "3159 W 21th Ave, Vancouver, BC V6L 1V9, Canada",
    City: "Vancouver",
    State: "BC ",
    "Zip code": "V6L 1V9",
    University: "Crofton House , Vancouver",
  },
  {
    Stt: 22,
    Name: "Abby Brock",
    Mail: "venoshstepansy309@gmail.com",
    "New Pass Mail": "cantelusviet@23",
    "Mail Reco": "stossvanleeryh786@gmail.com",
    "Pass Telus": "Telus#145",
    DOB: "28/7/1988",
    GEN: "Female",
    ADDRESS: "3236 W 24th Ave, Vancouver, BC V6L 1W1, Canada",
    City: "Vancouver",
    State: "BC ",
    "Zip code": "V6L 1W1",
    University: "Columbia International College, Ontario",
  },
  {
    Stt: 23,
    Name: "Hadley McCrae",
    Mail: "gasperbrotzmanwl720@gmail.com",
    "New Pass Mail": "cantelusviet@24",
    "Mail Reco": "venoshstepansy309@gmail.com",
    "Pass Telus": "Telus#146",
    DOB: "18/9/1988",
    GEN: "Female",
    ADDRESS: "3281 W 27th Ave, Vancouver, BC V6L 1W7, Canada",
    City: "Vancouver",
    State: "BC ",
    "Zip code": "V6L 1W7",
    University: "Albert College, Ontario",
  },
  {
    Stt: 24,
    Name: "Maggie Lee",
    Mail: "mattesonbelvealbr334@gmail.com",
    "New Pass Mail": "cantelusviet@25",
    "Mail Reco": "gasperbrotzmanwl720@gmail.com",
    "Pass Telus": "Telus#147",
    DOB: "27/2/1989",
    GEN: "Female",
    ADDRESS: "3454 W 26th Ave, Vancouver, BC V6S 1N5, Canada",
    City: "Vancouver",
    State: "BC ",
    "Zip code": "V6S 1N5",
    University: "Unionville, Unionville",
  },
  {
    Stt: 25,
    Name: "Aaliyah Foster",
    Mail: "rohrbachlipkindku350@gmail.com",
    "New Pass Mail": "cantelusviet@26",
    "Mail Reco": "mattesonbelvealbr334@gmail.com",
    "Pass Telus": "Telus#148",
    DOB: "26/2/1990",
    GEN: "Female",
    ADDRESS: "3820 W King Edward Ave, Vancouver, BC V6S 1N1, Canada",
    City: "Vancouver",
    State: "BC ",
    "Zip code": "V6S 1N1",
    University: "London Central, London",
  },
  {
    Stt: 26,
    Name: "Skylar Dawson",
    Mail: "manzerzupancicld313@gmail.com",
    "New Pass Mail": "cantelusviet@27",
    "Mail Reco": "rohrbachlipkindku350@gmail.com",
    "Pass Telus": "Telus#149",
    DOB: "12/3/1990",
    GEN: "Female",
    ADDRESS: "4276 Wallace St, Vancouver, BC V6S 2J4, Canada",
    City: "Vancouver",
    State: "BC ",
    "Zip code": "V6S 2J4",
    University: "Bayview, Richmond Hill",
  },
  {
    Stt: 27,
    Name: "Gemma Diamond",
    Mail: "riedelbumatayhr366@gmail.com",
    "New Pass Mail": "cantelusviet@28",
    "Mail Reco": "manzerzupancicld313@gmail.com",
    "Pass Telus": "Telus#150",
    DOB: "31/3/1990",
    GEN: "Female",
    ADDRESS: "4094 W 34th Ave, Vancouver, BC V6N 2L7, Canada",
    City: "Vancouver",
    State: "BC ",
    "Zip code": "V6N 2L7",
    University: "Southridge, Surrey",
  },
  {
    Stt: 28,
    Name: "Hana Nelson",
    Mail: "knightprevetpp918@gmail.com",
    "New Pass Mail": "cantelusviet@29",
    "Mail Reco": "riedelbumatayhr366@gmail.com",
    "Pass Telus": "Telus#151",
    DOB: "16/6/1991",
    GEN: "Female",
    ADDRESS: "6189 Elm St, Vancouver, BC V6N 1B2, Canada",
    City: "Vancouver",
    State: "BC ",
    "Zip code": "V6N 1B2",
    University: "Little Flower, Vancouver",
  },
  {
    Stt: 29,
    Name: "Eve Robinson",
    Mail: "imbertbozeot371@gmail.com",
    "New Pass Mail": "cantelusviet@30",
    "Mail Reco": "nanggylancov@outlook.com",
    "Pass Telus": "Telus#152",
    DOB: "14/9/1991",
    GEN: "Female",
    ADDRESS: "5970 Blenheim St, Vancouver, BC V6N 1R1, Canada",
    City: "Vancouver",
    State: "BC ",
    "Zip code": "V6N 1R1",
    University: "Lakefield College School, Lakefield",
  },
  {
    Stt: 30,
    Name: "Arianna Wheeler",
    Mail: "sorensonsteinkrauswm717@gmail.com",
    "New Pass Mail": "cantelusviet@31",
    "Mail Reco": "mustfindino0@outlook.com",
    "Pass Telus": "Telus#153",
    DOB: "14/9/1989",
    GEN: "Female",
    ADDRESS: "5616 Highbury St, Vancouver, BC V6N 1Y8, Canada",
    City: "Vancouver",
    State: "BC ",
    "Zip code": "V6N 1Y8",
    University: "Brentwood College School, Mill Bay",
  },
  {
    Stt: 31,
    Name: "Kayla Glen",
    Mail: "haschbescoyo398@gmail.com",
    "New Pass Mail": "cantelusviet@32",
    "Mail Reco": "fagonelezley3@outlook.com",
    "Pass Telus": "Telus#154",
    DOB: "16/1/1990",
    GEN: "Female",
    University: "Pickering College, Ontario",
  },
  {
    Stt: 32,
    Name: "Lena Regan",
    Mail: "mayorkroppgr954@gmail.com",
    "New Pass Mail": "cantelusviet@33",
    "Mail Reco": "huijseemaq@hotmail.com",
    "Pass Telus": "Telus#155",
    DOB: "12/2/1990",
    GEN: "Female",
    University: "West Point Grey, Vancouver",
  },
  {
    Stt: 33,
    Name: "Kaylee Baldwin",
    Mail: "rizerdeleouy150@gmail.com",
    "New Pass Mail": "cantelusviet@34",
    "Mail Reco": "akuppazourx@hotmail.com",
    "Pass Telus": "Telus#156",
    DOB: "19/6/1990",
    GEN: "Female",
    University: "St George’s, Vancouver",
  },
  {
    Stt: 34,
    Name: "Sadie Burt",
    Mail: "elstadshoyerys909@gmail.com",
    "New Pass Mail": "cantelusviet@35",
    "Mail Reco": "illutbiswssj@hotmail.com",
    "Pass Telus": "Telus#157",
    DOB: "27/6/1990",
    GEN: "Female",
    University: "Webber, Calgary",
  },
  {
    Stt: 35,
    Name: "Erin Point",
    Mail: "azebedoruzzoml750@gmail.com",
    "New Pass Mail": "cantelusviet@36",
    "Mail Reco": "cutiburian4@outlook.com",
    "Pass Telus": "Telus#158",
    DOB: "18/9/1990",
    GEN: "Female",
    University: "Ste Marguerite d’Youville, St. Albert",
  },
  {
    Stt: 36,
    Name: "Payton Bell",
    Mail: "innesvernonbs384@gmail.com",
    "New Pass Mail": "cantelusviet@37",
    "Mail Reco": "raimuushirou@hotmail.com",
    "Pass Telus": "Telus#159",
    DOB: "18/2/1991",
    GEN: "Female",
    University: "West Island College, Calgary",
  },
  {
    Stt: 37,
    Name: "Rachel Merritt",
    Mail: "thornsryherdqq338@gmail.com",
    "New Pass Mail": "cantelusviet@38",
    "Mail Reco": "mnallahingek@hotmail.com",
    "Pass Telus": "Telus#160",
    DOB: "16/05/1991",
    GEN: "Female",
    University: "Pierre Elliott Trudeau, Markham",
  },
  {
    Stt: 38,
    Name: "Molly Tyrell",
    Mail: "amspokerjedreyqs338@gmail.com",
    "New Pass Mail": "cantelusviet@39",
    "Mail Reco": "tarokhdebrayy@hotmail.com",
    "Pass Telus": "Telus#161",
    DOB: "16/07/1991",
    GEN: "Female",
    University: "St. Michaels University School, Victoria",
  },
  {
    Stt: 39,
    Name: "Kennedy Fisher",
    Mail: "carotenutomanchesterbi638@gmail.com",
    "New Pass Mail": "cantelusviet@40",
    "Mail Reco": "aabhanaqamus@hotmail.com",
    "Pass Telus": "Telus#162",
    DOB: "11/08/1991",
    GEN: "Female",
    University: "Ridley College, Ontario",
  },
  {
    Stt: 40,
    Name: "Nina Robertson",
    Mail: "stickneyjabbieus154@gmail.com",
    "New Pass Mail": "cantelusviet@41",
    "Mail Reco": "yomarabintunc@hotmail.com",
    "Pass Telus": "Telus#163",
    DOB: "22/08/1991",
    GEN: "Female",
    University: "Appleby College, Ontario",
  },
  {
    University: "Colonel By, Gloucester",
  },
  {
    University: "Iroquois Ridge, Oakville",
  },
  {
    University: "William Lyon Mackenzie, Toronto",
  },
  {
    University: "Cardinal Carter Academy for the Arts, Toronto",
  },
  {
    University: "Bur Oak, Markham",
  },
  {
    University: "St Michael, Kemptville",
  },
  {
    University: "West Carleton, Dunrobin",
  },
  {
    University: "St Robert, Thornhill",
    __EMPTY: "CanadaPOV#50",
  },
  {
    University: "AFNORTH International, Brunssum",
  },
  {
    University: "Brentwood College School, Cowichan Valley",
  },
];

const data = obj.map((item) => item.Name);
console.log(data);
